services:
  spring-boot-chanalyzer:
    image: "conorsheppard/spring-boot-chanalyzer"
    container_name: spring-boot-chanalyzer
    ports:
      - "8080:8080"
    environment:
      - SCRAPER_URL_LOCAL=http://playwright-java-scraper-chanalyzer:5050/api/v1/channels
      - SPRING.PROFILES.ACTIVE=default
    links:
      - playwright-java-scraper-chanalyzer
    build:
      context: ./spring-boot-chanalyzer
      dockerfile: docker-compose/Dockerfile-local
  react-chanalyzer:
    image: "conorsheppard/react-chanalyzer"
    container_name: react-chanalyzer
    ports:
      - "3000:3000"
    links:
      - spring-boot-chanalyzer
    build:
      context: ./react-chanalyzer
      dockerfile: docker-compose/Dockerfile-local
  playwright-java-scraper-chanalyzer:
    image: "conorsheppard/playwright-java-scraper-chanalyzer"
    container_name: playwright-java-scraper-chanalyzer
    ports:
      - "5050:5050"
    build:
      context: ./playwright-java-scraper-chanalyzer
      dockerfile: docker-compose/Dockerfile.local