services:
  spring-boot-chanalyzer:
    image: "conorsheppard/spring-boot-chanalyzer"
    container_name: spring-boot-chanalyzer
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    links:
      - playwright-java-scraper-chanalyzer
    build:
      context: ./spring-boot-chanalyzer
      dockerfile: docker-compose/Dockerfile
  react-chanalyzer:
    image: "conorsheppard/react-chanalyzer"
    container_name: react-chanalyzer
    ports:
      - "80:3000"
    links:
      - spring-boot-chanalyzer
    build:
      context: ./react-chanalyzer
      dockerfile: docker-compose/Dockerfile
  playwright-java-scraper-chanalyzer:
    image: "conorsheppard/playwright-java-scraper-chanalyzer"
    container_name: playwright-java-scraper-chanalyzer
    ports:
      - "5050:5050"
    build:
      context: ./playwright-java-scraper-chanalyzer
      dockerfile: docker-compose/Dockerfile