services:
  spring-boot-chanalyzer:
    image: "conorsheppard/spring-boot-chanalyzer"
    container_name: spring-boot-chanalyzer
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    links:
      - scraper-service-chanalyzer
    build:
      context: ./spring-boot-chanalyzer
      dockerfile: docker-compose/Dockerfile-local
  react-chanalyzer:
    image: "conorsheppard/react-chanalyzer"
    container_name: react-chanalyzer
    ports:
      - "80:3000"
    links:
      - spring-boot-chanalyzer
    build:
      context: ./react-chanalyzer
      dockerfile: docker-compose/Dockerfile-local
  scraper-service-chanalyzer:
    image: "conorsheppard/scraper-service-chanalyzer"
    container_name: scraper-service-chanalyzer
    ports:
      - "5050:5050"
    build:
      context: ./flask-scraper-service
      dockerfile: docker-compose/Dockerfile-local