version: '3'
services:

  spring-boot-chanalyzer:
    image: "conorsheppard/spring-boot-chanalyzer"
    container_name: spring-boot-chanalyzer
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    links:
      - scraper-service-chanalyzer
  react-chanalyzer:
    image: "conorsheppard/react-chanalyzer"
    container_name: react-chanalyzer
    ports:
      - "3000:3000"
    links:
      - spring-boot-chanalyzer
  scraper-service-chanalyzer:
    image: "conorsheppard/scraper-service-chanalyzer"
    container_name: scraper-service-chanalyzer
    ports:
      - "5050:5050"