spring:
  application:
    name: chanalyzer

SCRAPER_API: http://playwright-java-scraper-chanalyzer:5050/api/v1/channels
YT_BASE_URL: https://www.youtube.com/

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE