apiVersion: v1
kind: Service
metadata:
  name: react-chanalyzer-service
  labels:
    app: react-chanalyzer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
  selector:
    app: react-chanalyzer