name: yt-chanalyzer-build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
  - name: Build with Maven
    run: mvn -B test

  - name: Generate JaCoCo Badge
    uses: cicirello/jacoco-badge-generator@v2
    with:
      generate-branches-badge: true