#!/bin/zsh

mvn compile dependency:build-classpath -Dmdep.outputFile=classpath.txt
classpath=$(cat classpath.txt):target/classes
jshell --class-path "$classpath" --startup shell/jshell/startup.jsh shell/jshell/init.jsh
