FROM amazoncorretto:21-alpine-jdk
ARG JAR_FILE=target/chanalyzer-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} chanalyzer.jar
COPY application.properties application.properties
CMD [ "java", "-jar", "/chanalyzer.jar", "--spring.profiles.active=default" ]
EXPOSE 8080/tcp